import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";
import { Suspense } from "react";
import Loading from "./loading";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "./context/authcontext";
import { CartProvider } from "./context/cartContext";
import Providers from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Applebro Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <nav>
            <Navbar />
          </nav>
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <footer>
            <Footer />
          </footer>
          <ToastContainer />
        </body>
      </html>
    </Providers>
  );
}
